"""add orders and order items tables

Revision ID: 360850dbf1e2
Revises: 26dda572da73
Create Date: 2026-05-11 17:14:02.102897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360850dbf1e2'
down_revision = '26dda572da73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('shipping', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('shipping_name', sa.String(length=128), nullable=True),
    sa.Column('shipping_email', sa.String(length=254), nullable=True),
    sa.Column('shipping_address', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=64), nullable=True),
    sa.Column('shipping_state', sa.String(length=64), nullable=True),
    sa.Column('shipping_zip', sa.String(length=16), nullable=True),
    sa.Column('shipping_country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('product_sku', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
